version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: flight_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flight_data
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 20s

  dagster:
    build: .
    container_name: dagster_pipeline
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: flight_data
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    volumes:
      - .:/app
      - ./dagster_pipeline:/app/dagster_pipeline  
    ports:
      - "3000:3000"
    command: ["sh", "-c", "dagster dev -h 0.0.0.0 -p 3000 -f /app/dagster_pipeline/pipeline.py"]

volumes:
  mysql_data:
